---
node_name: 'MyNode-DOT' # Change this!
chain: polkadot
polkadot_network_id: polkadot
# Snapshot Provider: https://polkashots.io/
polkadot_db_snapshot_url: 'https://dot-rocksdb.polkashots.io/snapshot'
p2p_listen: 30333
# Keep these bound to 127.0.0.1 you otherwise expose the ports to the public!
rpc_listen: 127.0.0.1:9933
ws_listen: 127.0.0.1:9944
metrics_listen: 127.0.0.1:9615
db_path: '~/{{chain}}'
claimer_path: '~/{{chain}}-claimer'
api_endpoint: 'wss://rpc.polkadot.io/'
stash_addr: 'YOUR-STASH-ADDR-GOES-HERE'